#ifndef		__vpxver_h__
#define		__vpxver_h__
/*                                                                                   */
/*    +------------------------------------------------------------------------+     */
/*    + Copyright (c) 2000-2004 Renesas  Northern Japan Semiconductor,Inc.     +     */
/*    +------------------------------------------------------------------------+     */
/*    Title : VP-900 Serise PC Driver Version Infomation                             */
/*            SDK Version 1.60 Release                                               */
/*                                                                                   */

/*                                                                                   */
/*    PCDRV VERSION DEFINE                                                           */
/*              Major Version       0x01                                             */
/*              Minor Version       0x06                                             */
/*              Build               0x0001                                           */
/*                                                                                   */
#define			PCDRV_VERSION		0x01060001	/* Major/Minor/Build                 */
/*                                                                                   */
/*    PCDRV UPDATE DEFINE                                                            */
/*              Year      0x04                                                       */
/*              Month     0x02     (0x1 - 0x12)                                      */
/*              Day       0x05                                                       */
/*              Build     0x01                                                       */
/*                                                                                   */
#define			PCDRV_UPDATE		0x04020501	/* yyyy/m/dd/build                   */
/*                                                                                   */

/*                                                                                   */
/*    PCIDLL VERSION DEFINE                                                          */
/*              Major Version       0x01                                             */
/*              Minor Version       0x03                                             */
/*              Build               0x0001                                           */
/*                                                                                   */
#define			PCIDLL_VERSION		0x01030001	/* Major/Minor                       */
/*                                                                                   */
/*    TCPDLL VERSION DEFINE                                                          */
/*              Major Version       0x01                                             */
/*              Minor Version       0x03                                             */
/*              Build               0x0001                                           */
/*                                                                                   */
#define			TCPDLL_VERSION		0x01030001	/* Major/Minor                       */
/*                                                                                   */
/*    IPCMD VERSION DEFINE                                                           */
/*              Major Version       0x01                                             */
/*              Minor Version       0x06                                             */
/*              Build               0x0001                                           */
/*                                                                                   */
#define			IPCMD_VERSION		0x01060001	/* Major/Minor                       */
/*                                                                                   */
/*    IPSYS - ROM VERSION                                                            */
/*              Major Version       0x02                                             */
/*              Minor Version       0x00                                             */
/*              Build               0x0038                                           */
/*                                                                                   */
#define			ROM_VERSION			0x02000038	/* Major/Minor/Build                 */
/*                                                                                   */
/*    WINDOWS NT DRIVER VERSION                                                      */
/*              Major Version       0x01                                             */
/*              Minor Version       0x06                                             */
/*              Build               0x0001                                           */
/*                                                                                   */
#define			DEVDRV_VERSION		0x01060001	/* Major/Minor/Build                 */
/*                                                                                   */
/*    WINDOWS 2K WDM VERSION                                                         */
/*              Major Version       0x01                                             */
/*              Minor Version       0x06                                             */
/*              Build               0x0001                                           */
/*                                                                                   */
#define			WDMDRV_VERSION		0x01060001	/* Major/Minor/Build                 */
/*                                                                                   */

#endif /* !__vpxver_h__ */

