//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1022
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NagaraStage.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11000")]
        public int SurfThreshold {
            get {
                return ((int)(this["SurfThreshold"]));
            }
            set {
                this["SurfThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("215")]
        public int SurfStartRow {
            get {
                return ((int)(this["SurfStartRow"]));
            }
            set {
                this["SurfStartRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224")]
        public int SurfEndRow {
            get {
                return ((int)(this["SurfEndRow"]));
            }
            set {
                this["SurfEndRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int SurfNumSide {
            get {
                return ((int)(this["SurfNumSide"]));
            }
            set {
                this["SurfNumSide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double SurfDistance {
            get {
                return ((double)(this["SurfDistance"]));
            }
            set {
                this["SurfDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IndexUp {
            get {
                return ((double)(this["IndexUp"]));
            }
            set {
                this["IndexUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IndexDown {
            get {
                return ((double)(this["IndexDown"]));
            }
            set {
                this["IndexDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SurfaceVoting {
            get {
                return ((int)(this["SurfaceVoting"]));
            }
            set {
                this["SurfaceVoting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double SurfacePower {
            get {
                return ((double)(this["SurfacePower"]));
            }
            set {
                this["SurfacePower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SurfaceDelay {
            get {
                return ((int)(this["SurfaceDelay"]));
            }
            set {
                this["SurfaceDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int GridSpiral {
            get {
                return ((int)(this["GridSpiral"]));
            }
            set {
                this["GridSpiral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("252")]
        public double LimitPol {
            get {
                return ((double)(this["LimitPol"]));
            }
            set {
                this["LimitPol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public double EncoderResolutionX {
            get {
                return ((double)(this["EncoderResolutionX"]));
            }
            set {
                this["EncoderResolutionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public double EncoderResolutionY {
            get {
                return ((double)(this["EncoderResolutionY"]));
            }
            set {
                this["EncoderResolutionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0001")]
        public double EncoderResolutionZ {
            get {
                return ((double)(this["EncoderResolutionZ"]));
            }
            set {
                this["EncoderResolutionZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0005")]
        public double MotorResolutionX {
            get {
                return ((double)(this["MotorResolutionX"]));
            }
            set {
                this["MotorResolutionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0005")]
        public double MotorResolutionY {
            get {
                return ((double)(this["MotorResolutionY"]));
            }
            set {
                this["MotorResolutionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2E-05")]
        public double MotorResolutionZ {
            get {
                return ((double)(this["MotorResolutionZ"]));
            }
            set {
                this["MotorResolutionZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.02")]
        public double InitialVelocityX {
            get {
                return ((double)(this["InitialVelocityX"]));
            }
            set {
                this["InitialVelocityX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.02")]
        public double InitialVelocityY {
            get {
                return ((double)(this["InitialVelocityY"]));
            }
            set {
                this["InitialVelocityY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.004")]
        public double InitialVelocityZ {
            get {
                return ((double)(this["InitialVelocityZ"]));
            }
            set {
                this["InitialVelocityZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double AccelTimeX {
            get {
                return ((double)(this["AccelTimeX"]));
            }
            set {
                this["AccelTimeX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double AccelTimeY {
            get {
                return ((double)(this["AccelTimeY"]));
            }
            set {
                this["AccelTimeY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double AccelTimeZ {
            get {
                return ((double)(this["AccelTimeZ"]));
            }
            set {
                this["AccelTimeZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.03")]
        public double Speed1X {
            get {
                return ((double)(this["Speed1X"]));
            }
            set {
                this["Speed1X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.03")]
        public double Speed1Y {
            get {
                return ((double)(this["Speed1Y"]));
            }
            set {
                this["Speed1Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double Speed1Z {
            get {
                return ((double)(this["Speed1Z"]));
            }
            set {
                this["Speed1Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double Speed2X {
            get {
                return ((double)(this["Speed2X"]));
            }
            set {
                this["Speed2X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double Speed2Y {
            get {
                return ((double)(this["Speed2Y"]));
            }
            set {
                this["Speed2Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.02")]
        public double Speed2Z {
            get {
                return ((double)(this["Speed2Z"]));
            }
            set {
                this["Speed2Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double Speed3X {
            get {
                return ((double)(this["Speed3X"]));
            }
            set {
                this["Speed3X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double Speed3Y {
            get {
                return ((double)(this["Speed3Y"]));
            }
            set {
                this["Speed3Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.07")]
        public double Speed3Z {
            get {
                return ((double)(this["Speed3Z"]));
            }
            set {
                this["Speed3Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double Speed4X {
            get {
                return ((double)(this["Speed4X"]));
            }
            set {
                this["Speed4X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double Speed4Y {
            get {
                return ((double)(this["Speed4Y"]));
            }
            set {
                this["Speed4Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public double Speed4Z {
            get {
                return ((double)(this["Speed4Z"]));
            }
            set {
                this["Speed4Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-118")]
        public double ScanAreaXm {
            get {
                return ((double)(this["ScanAreaXm"]));
            }
            set {
                this["ScanAreaXm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118")]
        public double ScanAreaXp {
            get {
                return ((double)(this["ScanAreaXp"]));
            }
            set {
                this["ScanAreaXp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-118")]
        public double ScanAreaYm {
            get {
                return ((double)(this["ScanAreaYm"]));
            }
            set {
                this["ScanAreaYm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118")]
        public double ScanAreaYp {
            get {
                return ((double)(this["ScanAreaYp"]));
            }
            set {
                this["ScanAreaYp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ja-JP")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double SurfaceLoweringThin {
            get {
                return ((double)(this["SurfaceLoweringThin"]));
            }
            set {
                this["SurfaceLoweringThin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double SurfaceLoweringThick {
            get {
                return ((double)(this["SurfaceLoweringThick"]));
            }
            set {
                this["SurfaceLoweringThick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int SurfBinThreshold {
            get {
                return ((int)(this["SurfBinThreshold"]));
            }
            set {
                this["SurfBinThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double ShootInterval {
            get {
                return ((double)(this["ShootInterval"]));
            }
            set {
                this["ShootInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double ShootDistance {
            get {
                return ((double)(this["ShootDistance"]));
            }
            set {
                this["ShootDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string GridMarkLens {
            get {
                return ((string)(this["GridMarkLens"]));
            }
            set {
                this["GridMarkLens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string LedParam {
            get {
                return ((string)(this["LedParam"]));
            }
            set {
                this["LedParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double SurfaceMotorSpeed {
            get {
                return ((double)(this["SurfaceMotorSpeed"]));
            }
            set {
                this["SurfaceMotorSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int NumOfViewX {
            get {
                return ((int)(this["NumOfViewX"]));
            }
            set {
                this["NumOfViewX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int NumOfViewY {
            get {
                return ((int)(this["NumOfViewY"]));
            }
            set {
                this["NumOfViewY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OverAllScanDirectory {
            get {
                return ((string)(this["OverAllScanDirectory"]));
            }
            set {
                this["OverAllScanDirectory"] = value;
            }
        }
    }
}
