//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1022
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NagaraStage.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NagaraStage.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Abort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surface recognition is Aborted . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AbortedSurfaceRecognizing {
            get {
                return ResourceManager.GetString("AbortedSurfaceRecognizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grid Mark Search is Aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AbortGridMarkSearch {
            get {
                return ResourceManager.GetString("AbortGridMarkSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abort motor moving. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AbortMotor {
            get {
                return ResourceManager.GetString("AbortMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accumulative に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Accum {
            get {
                return ResourceManager.GetString("Accum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Activity was aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityAbort {
            get {
                return ResourceManager.GetString("ActivityAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Activity is already running. Do you abort it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityActiveException01 {
            get {
                return ResourceManager.GetString("ActivityActiveException01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Activity is running now. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityRunning {
            get {
                return ResourceManager.GetString("ActivityRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adjust Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdjustLight {
            get {
                return ResourceManager.GetString("AdjustLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Tracks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllTracks {
            get {
                return ResourceManager.GetString("AllTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Append に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Append {
            get {
                return ResourceManager.GetString("Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you append this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppendSave {
            get {
                return ResourceManager.GetString("AppendSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply and reboot. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplyReboot {
            get {
                return ResourceManager.GetString("ApplyReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you abort it ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AskAbort {
            get {
                return ResourceManager.GetString("AskAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you set, really? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AskReallySetting {
            get {
                return ResourceManager.GetString("AskReallySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attention に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic Detection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoDetect {
            get {
                return ResourceManager.GetString("AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic Tracking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoTracking {
            get {
                return ResourceManager.GetString("AutoTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back to Origin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackOrigin {
            get {
                return ResourceManager.GetString("BackOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beam Sport Detect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BeamDetect {
            get {
                return ResourceManager.GetString("BeamDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Threshold for Binarize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BinarizeThreshold {
            get {
                return ResourceManager.GetString("BinarizeThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boundary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Boundary {
            get {
                return ResourceManager.GetString("Boundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brightness に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Threshold of brightness に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrightnessThreshold {
            get {
                return ResourceManager.GetString("BrightnessThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera is not working. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraNotWork {
            get {
                return ResourceManager.GetString("CameraNotWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeDate {
            get {
                return ResourceManager.GetString("ChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete surface recognizing． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompletedSurfaceRecognizing {
            get {
                return ResourceManager.GetString("CompletedSurfaceRecognizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CoordHint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CoordHint {
            get {
                return ResourceManager.GetString("CoordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coordinate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Coordinate {
            get {
                return ResourceManager.GetString("Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coord Sysmtem に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CoordSystem {
            get {
                return ResourceManager.GetString("CoordSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating Coord に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CoordTab {
            get {
                return ResourceManager.GetString("CoordTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Correct lens type is {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CorrectLens {
            get {
                return ResourceManager.GetString("CorrectLens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Coord System に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateCoordSystem {
            get {
                return ResourceManager.GetString("CreateCoordSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decide Grid mark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DecideGridMark {
            get {
                return ResourceManager.GetString("DecideGridMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Defalut value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is defined now. ({1}, {2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefineGridMark {
            get {
                return ResourceManager.GetString("DefineGridMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delay time (msec) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DelayTime {
            get {
                return ResourceManager.GetString("DelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestinationDir {
            get {
                return ResourceManager.GetString("DestinationDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detect Grid marks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DetectGridMark {
            get {
                return ResourceManager.GetString("DetectGridMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Determin in Gel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DetermineInGel {
            get {
                return ResourceManager.GetString("DetermineInGel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Direction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The folder is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DirNotFound {
            get {
                return ResourceManager.GetString("DirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dsitance to abort(um) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DistanceOut {
            get {
                return ResourceManager.GetString("DistanceOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw Coordinate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DrawCoord {
            get {
                return ResourceManager.GetString("DrawCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw Emulsion Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DrawEmulsionInfo {
            get {
                return ResourceManager.GetString("DrawEmulsionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw Figures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DrawFigures {
            get {
                return ResourceManager.GetString("DrawFigures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emulsion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Emulsion {
            get {
                return ResourceManager.GetString("Emulsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emulsion Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmulsionInformation {
            get {
                return ResourceManager.GetString("EmulsionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emulsion type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmulstionType {
            get {
                return ResourceManager.GetString("EmulstionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EndPosition {
            get {
                return ResourceManager.GetString("EndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End row に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EndRow {
            get {
                return ResourceManager.GetString("EndRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed surface recognizing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FailedSurfaceRecognizing {
            get {
                return ResourceManager.GetString("FailedSurfaceRecognizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fast Surface Recognition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FastSurfaceRecognition {
            get {
                return ResourceManager.GetString("FastSurfaceRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileAlreadyExist {
            get {
                return ResourceManager.GetString("FileAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File extension is not avairable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileExtensionNotAvairable {
            get {
                return ResourceManager.GetString("FileExtensionNotAvairable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileNameInvalid {
            get {
                return ResourceManager.GetString("FileNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Folder is not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FolderNotExists {
            get {
                return ResourceManager.GetString("FolderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is found now. ({1}, {2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FoundNow {
            get {
                return ResourceManager.GetString("FoundNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full Scan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FullScan {
            get {
                return ResourceManager.GetString("FullScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Gel {
            get {
                return ResourceManager.GetString("Gel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center Top Grid mark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMakrCenterTop {
            get {
                return ResourceManager.GetString("GridMakrCenterTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grid mark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMark {
            get {
                return ResourceManager.GetString("GridMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center Bottom Grid mark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMarkCenterBottom {
            get {
                return ResourceManager.GetString("GridMarkCenterBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center Middle Grid mark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMarkCenterMiddle {
            get {
                return ResourceManager.GetString("GridMarkCenterMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you define here as {0}? Click &quot;Yes&quot; if you define as {0}. Or Click &quot;No&quot; if you define as other grid mark. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridmarkDialog01 {
            get {
                return ResourceManager.GetString("GridmarkDialog01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Bottom Grid mark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMarkLeftBottom {
            get {
                return ResourceManager.GetString("GridMarkLeftBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Middle Grid mark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMarkLeftMiddle {
            get {
                return ResourceManager.GetString("GridMarkLeftMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Top Grid mark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMarkLeftTop {
            get {
                return ResourceManager.GetString("GridMarkLeftTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Number of defined grid marks id too few. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMarkNotDefinedMin {
            get {
                return ResourceManager.GetString("GridMarkNotDefinedMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Grid mark is not still defined. Move to the Predicted Coordinate? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMarkNotExistedPredMove {
            get {
                return ResourceManager.GetString("GridMarkNotExistedPredMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed grid mark searching. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMarkNotFoundException01 {
            get {
                return ResourceManager.GetString("GridMarkNotFoundException01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Bottom Grid mark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMarkRightBottom {
            get {
                return ResourceManager.GetString("GridMarkRightBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Middle Grid mark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMarkRightMiddle {
            get {
                return ResourceManager.GetString("GridMarkRightMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Top Grid mark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMarkRightTop {
            get {
                return ResourceManager.GetString("GridMarkRightTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grid Mark Search is Completed! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMarkSearchComplete {
            get {
                return ResourceManager.GetString("GridMarkSearchComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grid Mark Search is Failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMarkSearchFailed {
            get {
                return ResourceManager.GetString("GridMarkSearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grid Mark Search is start. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridMarkSearchStart {
            get {
                return ResourceManager.GetString("GridMarkSearchStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hit# に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HitSharp {
            get {
                return ResourceManager.GetString("HitSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Enhancement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageEnhancement {
            get {
                return ResourceManager.GetString("ImageEnhancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageFile {
            get {
                return ResourceManager.GetString("ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indes value is far from 2. Is it true? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexFarExceptionWarning {
            get {
                return ResourceManager.GetString("IndexFarExceptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index Measure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexMeasure {
            get {
                return ResourceManager.GetString("IndexMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index value must be lager than 1. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexTooSmallException {
            get {
                return ResourceManager.GetString("IndexTooSmallException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file memorized index value is not found at {0}. Do you set it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexValueNotFound {
            get {
                return ResourceManager.GetString("IndexValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indicative Brightness に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndicativeBrightness {
            get {
                return ResourceManager.GetString("IndicativeBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In the Gel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InGel {
            get {
                return ResourceManager.GetString("InGel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializing Camera is failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitCameraExcetion01 {
            get {
                return ResourceManager.GetString("InitCameraExcetion01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Defined Grid marks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitGridMark {
            get {
                return ResourceManager.GetString("InitGridMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you realy clear defined Grid marks? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitGridMarkReally {
            get {
                return ResourceManager.GetString("InitGridMarkReally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializing LED is failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitLedException01 {
            get {
                return ResourceManager.GetString("InitLedException01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializing Motor Controler Board is failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitMotorException01 {
            get {
                return ResourceManager.GetString("InitMotorException01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializing Parameters is failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitParamException01 {
            get {
                return ResourceManager.GetString("InitParamException01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inputed value is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputInvalidValue {
            get {
                return ResourceManager.GetString("InputInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is Inside gel now. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InsideGelNow {
            get {
                return ResourceManager.GetString("InsideGelNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Judge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Judge {
            get {
                return ResourceManager.GetString("Judge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you realy set {0} language ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LangSelect01 {
            get {
                return ResourceManager.GetString("LangSelect01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language setting has been changed. It is available after reboot the Application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LangSelect02 {
            get {
                return ResourceManager.GetString("LangSelect02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language select is failed. So, selected System Language. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LangSelectException01 {
            get {
                return ResourceManager.GetString("LangSelectException01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Led {
            get {
                return ResourceManager.GetString("Led", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LeftBottom {
            get {
                return ResourceManager.GetString("LeftBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LeftTop {
            get {
                return ResourceManager.GetString("LeftTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lens node doesn&apos;t have Necessary item(s) at {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LensNodeParseException01 {
            get {
                return ResourceManager.GetString("LensNodeParseException01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lens Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LensType {
            get {
                return ResourceManager.GetString("LensType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lens type is not correct. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LensTypeException01 {
            get {
                return ResourceManager.GetString("LensTypeException01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lens type setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LensTypeSetting {
            get {
                return ResourceManager.GetString("LensTypeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadData {
            get {
                return ResourceManager.GetString("LoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadIndex {
            get {
                return ResourceManager.GetString("LoadIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lower Gel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LowerGel {
            get {
                return ResourceManager.GetString("LowerGel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom of Lower gel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LowerGelBottom {
            get {
                return ResourceManager.GetString("LowerGelBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top of Lower gel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LowerGelTop {
            get {
                return ResourceManager.GetString("LowerGelTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MailAddress {
            get {
                return ResourceManager.GetString("MailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Meas Brightness に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeasBrightness {
            get {
                return ResourceManager.GetString("MeasBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Measurement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Measurement {
            get {
                return ResourceManager.GetString("Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minus Direction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MinusDirection {
            get {
                return ResourceManager.GetString("MinusDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Module No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModuleNo {
            get {
                return ResourceManager.GetString("ModuleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Module No. must be 1-45 or 51-100. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModuleNoOutOfRangeException {
            get {
                return ResourceManager.GetString("ModuleNoOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor is moving now. Do you abort the present motor action? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MotorActive01 {
            get {
                return ResourceManager.GetString("MotorActive01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor is moving now. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MotorActiveException01 {
            get {
                return ResourceManager.GetString("MotorActiveException01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This command is canceld now because motor is active now. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MotorActiveException02 {
            get {
                return ResourceManager.GetString("MotorActiveException02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor Limit: - direction. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MotorAxisLimitMinus {
            get {
                return ResourceManager.GetString("MotorAxisLimitMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor Limit: + direction. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MotorAxisLimitPlus {
            get {
                return ResourceManager.GetString("MotorAxisLimitPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor Controllable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MotorControllable {
            get {
                return ResourceManager.GetString("MotorControllable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor: Over Heat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MotorOverHeat {
            get {
                return ResourceManager.GetString("MotorOverHeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor moving is stopped by user`s request. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MotorStop01 {
            get {
                return ResourceManager.GetString("MotorStop01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to the Coord. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveToCoord {
            get {
                return ResourceManager.GetString("MoveToCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to surface に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveToSurface {
            get {
                return ResourceManager.GetString("MoveToSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moving... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Moving {
            get {
                return ResourceManager.GetString("Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete moving. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MovingComplete {
            get {
                return ResourceManager.GetString("MovingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Stage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewStage {
            get {
                return ResourceManager.GetString("NewStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let&apos;s set up the New Stage.
        ///First, Enter your name and a mail address. Entering Mail address is voluntary.
        ///Next, Select the emulsion number you using. Enter plate No., module No. and select emulsion type, Thick or Thin. &quot;Index&quot; means the thickness of emulsion layers. &quot;Up Index&quot;  is the thickness of Upper gel, &quot;Under Index&quot; is the thickness of Lower gel. 
        ///And, there shold be files having Emulsion information. Enter the file path to appropritate emulsion you using.
        ///Last, Click the OK button.
        ///Last, Click  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewStageHelp {
            get {
                return ResourceManager.GetString("NewStageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewStart {
            get {
                return ResourceManager.GetString("NewStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Grid mark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NextGridMark {
            get {
                return ResourceManager.GetString("NextGridMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Track に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NextTrack {
            get {
                return ResourceManager.GetString("NextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The controll is unavailable now. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoControllable {
            get {
                return ResourceManager.GetString("NoControllable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The length of side to average brightness (pxcel) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NumOfSidePixcel {
            get {
                return ResourceManager.GetString("NumOfSidePixcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of Voting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NumOfVoting {
            get {
                return ResourceManager.GetString("NumOfVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Prediction File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenPred {
            get {
                return ResourceManager.GetString("OpenPred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Scaned File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenScan {
            get {
                return ResourceManager.GetString("OpenScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original Point is changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OriginChanged {
            get {
                return ResourceManager.GetString("OriginChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other Grid marks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OtherGridMarks {
            get {
                return ResourceManager.GetString("OtherGridMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is Outside gel Now. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OutsideGelNow {
            get {
                return ResourceManager.GetString("OutsideGelNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Over Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OverIndex {
            get {
                return ResourceManager.GetString("OverIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pixcel Format must be Gray8. 8bit 256 colors gray scale is accepted only. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PixcelFormatException {
            get {
                return ResourceManager.GetString("PixcelFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plate No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlateNo {
            get {
                return ResourceManager.GetString("PlateNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PlateNo. must be integer than 1. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlateNoInavilityException {
            get {
                return ResourceManager.GetString("PlateNoInavilityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plurality に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Plurality {
            get {
                return ResourceManager.GetString("Plurality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plus Direction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlusDirection {
            get {
                return ResourceManager.GetString("PlusDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power Value of Difference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PowerOfDifference {
            get {
                return ResourceManager.GetString("PowerOfDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prediction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prediction {
            get {
                return ResourceManager.GetString("Prediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press any key for abort. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PressAnyKeyForAbort {
            get {
                return ResourceManager.GetString("PressAnyKeyForAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Grid mark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreviousGridMark {
            get {
                return ResourceManager.GetString("PreviousGridMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Refference {
            get {
                return ResourceManager.GetString("Refference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Boundary flag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveBoundaryFlag {
            get {
                return ResourceManager.GetString("RemoveBoundaryFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RightBottom {
            get {
                return ResourceManager.GetString("RightBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RightTop {
            get {
                return ResourceManager.GetString("RightTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scan File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScanFile {
            get {
                return ResourceManager.GetString("ScanFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Emulsion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectEmulsion {
            get {
                return ResourceManager.GetString("SelectEmulsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Folder to Save Images. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFolderToSave {
            get {
                return ResourceManager.GetString("SelectFolderToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select which is grid mark. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectWhichGridMark {
            get {
                return ResourceManager.GetString("SelectWhichGridMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Semi Automatic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SemiAuto {
            get {
                return ResourceManager.GetString("SemiAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Boundary flag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetBoundaryFlag {
            get {
                return ResourceManager.GetString("SetBoundaryFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click &quot;OK&quot; after Set lens of the microscope to {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetLensDialog {
            get {
                return ResourceManager.GetString("SetLensDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set X{0} lens に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetLensXMag {
            get {
                return ResourceManager.GetString("SetLensXMag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Origin Here に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetOrigin {
            get {
                return ResourceManager.GetString("SetOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Spiral Origin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetSpiralOrigin {
            get {
                return ResourceManager.GetString("SetSpiralOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set {0} flag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetXFlag {
            get {
                return ResourceManager.GetString("SetXFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shooting Pictures is active. Do you abort? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShootException01 {
            get {
                return ResourceManager.GetString("ShootException01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shooting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shooting {
            get {
                return ResourceManager.GetString("Shooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Slice {
            get {
                return ResourceManager.GetString("Slice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Software is already booting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SoftwareAlreadyBoot {
            get {
                return ResourceManager.GetString("SoftwareAlreadyBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Stage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SoftwareName {
            get {
                return ResourceManager.GetString("SoftwareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   speed1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Speed1 {
            get {
                return ResourceManager.GetString("Speed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   speed2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Speed2 {
            get {
                return ResourceManager.GetString("Speed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   speed3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Speed3 {
            get {
                return ResourceManager.GetString("Speed3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   speed4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Speed4 {
            get {
                return ResourceManager.GetString("Speed4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back to Spiral Origin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpiralBack {
            get {
                return ResourceManager.GetString("SpiralBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spiral Move に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpiralMove {
            get {
                return ResourceManager.GetString("SpiralMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stage is running now. Do you finish the stage? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StageRunAbort {
            get {
                return ResourceManager.GetString("StageRunAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Started surface recognizing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartedSurfaceRecognizing {
            get {
                return ResourceManager.GetString("StartedSurfaceRecognizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartPosition {
            get {
                return ResourceManager.GetString("StartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start row に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRow {
            get {
                return ResourceManager.GetString("StartRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surface に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Surface {
            get {
                return ResourceManager.GetString("Surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Binarize not run, in case you set less than or equal to 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceBinThresholdMessage01 {
            get {
                return ResourceManager.GetString("SurfaceBinThresholdMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surface Recognizing: Complete! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceComplete {
            get {
                return ResourceManager.GetString("SurfaceComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surface Recognizing Configure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceConfig {
            get {
                return ResourceManager.GetString("SurfaceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distance from Start Pint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceDistance {
            get {
                return ResourceManager.GetString("SurfaceDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surface Recognizing: Bottom of Down Gel is at {0}.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceDownBottomRecognized {
            get {
                return ResourceManager.GetString("SurfaceDownBottomRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surface Recognizing: Top of Down Gel is at {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceDownTopRecognized {
            get {
                return ResourceManager.GetString("SurfaceDownTopRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor is moving now. Motor need to be stop for surface recognizing. Do you stop motor?  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceException01 {
            get {
                return ResourceManager.GetString("SurfaceException01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surface recognizing task is already active  now. Do you abort it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceException02 {
            get {
                return ResourceManager.GetString("SurfaceException02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lowering Distance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceLoweringDistance {
            get {
                return ResourceManager.GetString("SurfaceLoweringDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surface Recognizing: Motor got to Bottom Limit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceOnBttomLimited {
            get {
                return ResourceManager.GetString("SurfaceOnBttomLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surface Recognize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceRecog {
            get {
                return ResourceManager.GetString("SurfaceRecog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surface Recognition started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceStart {
            get {
                return ResourceManager.GetString("SurfaceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surface Recognizing: Bottom of Up Gel is at {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceUpBottomRecognized {
            get {
                return ResourceManager.GetString("SurfaceUpBottomRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surface Recognizing: Top of Up Gel is at {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceUpTopRecognizing {
            get {
                return ResourceManager.GetString("SurfaceUpTopRecognizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surface Recognition Verification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SurfaceVerif {
            get {
                return ResourceManager.GetString("SurfaceVerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Configure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SystemConfigure {
            get {
                return ResourceManager.GetString("SystemConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning: Incorrect settings may not be able to operate correctly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SystemConfWarning {
            get {
                return ResourceManager.GetString("SystemConfWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Take Accumlative Picture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TakeAccumlative {
            get {
                return ResourceManager.GetString("TakeAccumlative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Take Plurality Pictures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TakePlurality {
            get {
                return ResourceManager.GetString("TakePlurality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Take Single Picture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TakeSingle {
            get {
                return ResourceManager.GetString("TakeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thick type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThickType {
            get {
                return ResourceManager.GetString("ThickType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thin type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThinType {
            get {
                return ResourceManager.GetString("ThinType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Track に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All tracks are already completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrackFoundComplete {
            get {
                return ResourceManager.GetString("TrackFoundComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Track ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrackId {
            get {
                return ResourceManager.GetString("TrackId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Track Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrackInfo {
            get {
                return ResourceManager.GetString("TrackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Track information is not loaded. First, Load tracks information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TracksManagerException01 {
            get {
                return ResourceManager.GetString("TracksManagerException01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnderIndex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnderIndex {
            get {
                return ResourceManager.GetString("UnderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upper Gel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpperGel {
            get {
                return ResourceManager.GetString("UpperGel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom of Upper gel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpperGelBottom {
            get {
                return ResourceManager.GetString("UpperGelBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top of Upper gel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpperGelTop {
            get {
                return ResourceManager.GetString("UpperGelTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be more than {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValMustMore {
            get {
                return ResourceManager.GetString("ValMustMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be an odd number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValMustOdd {
            get {
                return ResourceManager.GetString("ValMustOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be {1} or more に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValMustOrMore {
            get {
                return ResourceManager.GetString("ValMustOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be a positive number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValMustPositive {
            get {
                return ResourceManager.GetString("ValMustPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be a positive number with 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValMustPositiveNotZero {
            get {
                return ResourceManager.GetString("ValMustPositiveNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is too large. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValTooLarge {
            get {
                return ResourceManager.GetString("ValTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is too small. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValTooSmall {
            get {
                return ResourceManager.GetString("ValTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Verif {
            get {
                return ResourceManager.GetString("Verif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All grid marks are not defined. But can create Coord System. Do you continu to create it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WarnCreateCoord01 {
            get {
                return ResourceManager.GetString("WarnCreateCoord01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Which Grid mark you attempting to define? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WhichGridMark {
            get {
                return ResourceManager.GetString("WhichGridMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
